// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxapseqymqcnnhpczjpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4YXBzZXF5bXFjbm5ocGN6anBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NjI0OTcsImV4cCI6MjA4NzMzODQ5N30.zhZAFDfzYa2ZLKliUKuiIlNJ1eZ_bEO2LhS5C5dHgqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});